<pre><?= $block->getResponsiveSlickSettings(); ?></pre>
<?php
 $slides = $block->getSlides();
 if(count($slides)):
?>

 <div id="<?= $block->getId() ?>" class="usslick__slider" <?php if($block->isResponsive()) :?>data-slick='<?= $block->getResponsiveSlickSettings(); ?>'<?php endif; ?>>

  <?php
   foreach($slides as $slide):
    $status = $slide['status'];
    $title = $slide['title'];
    $alt = $slide['alt'];
    $link = $slide['link'];
    $image = $slide['image'];
    $getLink = $block->getSlideLink($link);
    $getImage = $block->getSlideImage($image);
    $isNewTab = $block->getSlideTarget($link);
   ?>
   
  <?php if($status && $image): ?>
  <div class="usslick__slide">
    
   <?php if($getLink) : ?>
   <a href="<?= $getLink ?>" title="<?= $title ?>" class="usslick__slide--link" <?= ($isNewTab) ? 'target="_blank"': '' ?>>
   <?php else: ?>
   <div class="usslick__slide--unlink">
   <?php endif; ?>

    <img src="<?= $getImage ?>" alt="<?= $alt ?>" title="<?= $title ?>" class="usslick__slide--image" />

   <?php if($getLink) : ?>
   </a>
   <?php else: ?>
   </div>
   <?php endif; ?>

  </div>
  <?php endif; ?>

  <?php endforeach; ?>

 </div>

<?php endif; ?>

<pre><?= json_encode($this->getData('slider_data'),JSON_PRETTY_PRINT) ?></pre>

<script>
 require([
  'jquery',
  'matchMedia',
  'slick'
 ], function($, mediaCheck, slick) {

   var $slick_slider = $('#<?= $block->getId() ?>');
   $slick_slider.slick(<?= $block->getSlickSettings(); ?>);


  //  mediaCheck({
  //   media: '(max-width: 699px)',
  //   entry: function() {
     
  //    if($slick_slider.hasClass('slick-initialized'))
  //     $slick_slider.slick('unslick');
  //    return
  //   },
  //   exit: function() {
  //    if(!$slick_slider.hasClass('slick-initialized'))
  //     return $slick_slider.slick("resize");;
  //    }
  //  });



 });
</script>

<pre><?= $block->getStylesheets(); ?></pre>







