<?php
 $slides = $block->getSlides();
 if(count($slides)):
?>

 <div id="<?= $block->getId() ?>" class="usslick__slider">

  <?php
   foreach($slides as $slide):
    $status = $slide['status'];
    $title = $slide['title'];
    $alt = $slide['alt'];
    $link = $slide['link'];
    $image = $slide['image'];
    $getLink = $block->getLink($link);
    $getTarget = $block->getTarget($link);
    $getImage = $block->getImage($image);
   ?>
   
  <?php if($status && $image): ?>
  <div class="usslick__slide">
    
   <?php if($getLink) : ?>
   <a href="<?= $getLink ?>" title="<?= $title ?>" class="usslick__slide--link" <?= $getTarget ?>>
   <?php else: ?>
   <div class="usslick__slide--unlink">
   <?php endif; ?>

    <img src="<?= $getImage ?>" alt="<?= $alt ?>" title="<?= $title ?>" class="usslick__slide--image" />

   <?php if($getLink) : ?>
   </a>
   <?php else: ?>
   </div>
   <?php endif; ?>

  </div>
  <?php endif; ?>

  <?php endforeach; ?>

 </div>

<?php endif; ?>

<pre><?= json_encode($block->getParentData(),JSON_PRETTY_PRINT) ?></pre>
<br/>
<pre><?= json_encode($block->getResponsiveData(),JSON_PRETTY_PRINT) ?></pre>

<br/>
<pre><?= json_encode($block->getResponsiveSlickSettings(),JSON_PRETTY_PRINT) ?></pre>

<br/>
<pre><?= json_encode($block->getSlickSettings(),JSON_PRETTY_PRINT) ?></pre>


<script>
 require([
  'jquery',
  'slick'
 ], function($, slick) {
  var $window = $(window);
  var $slick_slider = $('#<?= $block->getId() ?>');
  var settings = {
    "arrows": true,
    "dots": false,
    "infinite": true,
    "speed": 300,
    "autoplay": false,
    "centerMode": false,
    "adaptiveHeight": true,
    "slidesToShow": 4,
    "slidesToScroll": 1,
    "responsive": [    
      {
            "breakpoint": 768,
            "settings": "unslick"
        },
        {
            "breakpoint": 992,
            "settings": {
                "arrows": true,
                "dots": false,
                "infinite": true,
                "speed": 300,
                "autoplay": true,
                "autoplaySpeed": 4000,
                "slidesToShow": 2,
                "slidesToScroll": 1
            }
        },
        
    
        {
            "breakpoint": 1200,
            "settings": {
                "arrows": true,
                "dots": false,
                "infinite": true,
                "speed": 300,
                "autoplay": false,
                "centerMode": false,
                "slidesToShow": 3,
                "slidesToScroll": 1
            }
        }
    ]
};




$slick_slider.slick(settings);

$window.on('resize', function() {
  if ($window.width() < 640) {
    if ($slick_slider.hasClass('slick-initialized'))
    setTimeout(function(){ $slick_slider.slick('unslick'); },100);
    return
  }
  if (!$slick_slider.hasClass('slick-initialized'))
    return setTimeout(function(){$slick_slider.slick(settings)},100);
});  

 


 });
</script>

<pre><?= $block->getStylesheets(); ?></pre>







